name: Food Bytes
favicon: null
layout_spectrum: 0.2538
typography_spectrum: 0.009199177846312523
title: Food Bytes
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#005f00'
    - '#ffffff'
    - '#9ea800'
    - '#000000'
    - '#00ff00'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
