name: Food Bytes
favicon: null
layout_spectrum: 0.7958074654452503
typography_spectrum: 0.009199177846312523
title: Food Bytes
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.07386230444535613
  lightness: 0.5100108066108078
  saturation: 0.42903841915540397
  rhythmicContrast: 0.832469466375187
purpose: []
